---
title: "STL"
author: "Song Qian"
date: "11/8/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
packages(stlplus)

median.polish.ts <- function(data.ts, ylab="", plt=T){
  # median polishing for missing value imputation
  medpolish(matrix(data.ts, ncol=12, byrow=T), eps=0.001, na.rm=T)->temp.2w
  print(names(temp.2w))
  year.temp <- rep(seq(start(data.ts)[1], end(data.ts)[1]), each=12)
  month.temp <- rep(1:12, length(seq(start(data.ts)[1], end(data.ts)[1])))
  # plotting median polishing results
  if (plt){
    par(mfrow=c(2,1))
    plot(seq(start(data.ts)[1], end(data.ts)[1]),
         temp.2w$overall+temp.2w$row, type="l",
         xlab="Year", ylab=ylab, main="De-seasonalized Trend")
    plot(seq(1,12), temp.2w$overall+temp.2w$col, type="l",
         xlab="Month", ylab=ylab, main="Seasonal Changes")
  }
  data.ts[is.na(data.ts)]<-temp.2w$overall +
    temp.2w$row[year.temp[is.na(data.ts)]-start(data.ts)[1]+1]+
      temp.2w$col[month.temp[is.na(data.ts)]]
  data.ts[is.na(data.ts)]<-temp.2w$overall
  invisible(data.ts)
}
```

## The CO~2~ Data

STL: seasonal-trend decomposition using loess (Cleveland, Cleveland, McRae, and Terpenning, 1990. *Journal of Official Statistics*, 6(1): 3-73)

Here is the classic R implementation of STL (function `stl`) based on Cleveland's original S-Plus code:
```{R STL}
data <- carbon.dioxide
ylab <- "Carbon Dioxide (ppm)"
aspect <- "xy"
the.fit <- stl(data, s.window = 25, s.degree = 1, t.window = 120,
                   t.degree = 1)

    sfit <- the.fit$time.series[,1]
    tfit <- the.fit$time.series[,2]
    fit.time <- time(data)
    car.subseries <- factor(cycle(data), label = month.abb)
    obj1.df <- data.frame(y=sfit, x=fit.time, cat=car.subseries)

    obj1 <- xyplot(sfit ~ fit.time | car.subseries, layout = c(12, 1), panel = function(x, y){
        panel.xyplot(x, y, type = "l")
        panel.abline(h = mean(y))}, 
##        aspect = aspect, 
        xlab = "Year", ylab = ylab)

    obj2.df <- data.frame(y=tfit, x=fit.time)
    obj2 <- xyplot(tfit ~ fit.time, panel = function(x, y)
        panel.xyplot(x, y, type = "l"), xlab = "", aspect = "xy", ylab = "")

    n <- length(data)
    the.fit.trend <- the.fit$time.series[,2] - mean(the.fit$time.series[,2])
    fit.components <- c(the.fit.trend, the.fit$time.series[,1], the.fit$time.series[,3])
    fit.time <- rep(time(data), 3)
    fit.names <- ordered(rep(c("Trend", "Seasonality", "Residuals"), c(n, n, n)),
                         c("Trend", "Seasonality", "Residuals"))

    obj3.df <- data.frame(x=fit.time, y=fit.components, series=fit.names)
    obj3 <- xyplot(fit.components ~ fit.time | fit.names, panel = function(x, y){
        panel.grid(h = 5)
        panel.xyplot(x, y, type = "l")
        }, 
        aspect=0.75, layout = c(3, 1), ylim = c(-1, 1) * max(abs(fit.components)),
        xlab = "", ylab = ylab)
    print(obj1, position = c(0, 0, 1, 0.5), more = T)
    print(obj3, position = c(0, 0.5, 1, 1), more = F)

```
Examples from R package `stlplus`.

```{r STLplus}

co2_stl <- stlplus(co2, t = as.vector(time(co2)), n.p = 12,
  l.window = 13, t.window = 19, s.window = 35, s.degree = 1,
  sub.labels = substr(month.name, 1, 3))

plot(co2_stl, ylab = "CO2 Concentration (ppm)", xlab = "Time (years)")
plot_seasonal(co2_stl)
plot_trend(co2_stl)
plot_cycle(co2_stl)
plot_rembycycle(co2_stl)

# post-trend smoothing

co2_stl_pt <- stlplus(co2, t = as.vector(time(co2)), n.p = 12,
  l.window = 13, t.window = 19, s.window = 35, s.degree = 1,
  sub.labels = substr(month.name, 1, 3),
  fc.degree = c(1, 2), fc.window = c(201, 35),
  fc.name = c("long-term", "so. osc."))

plot(co2_stl_pt, scales = list(y = list(relation = "free")),
  ylab = "CO2 Concentration (ppm)", xlab = "Time (years)",
  aspect = 0.25, type = c("l", "g"))

# with NAs

y <- co2
y[201:224] <- NA

y_stl <- stlplus(y, l.window = 13, t.window = 19, s.window = 35,
  s.degree = 1, sub.labels = substr(month.name, 1, 3))

plot(y_stl, ylab = "CO2 Concentration (ppm)", xlab = "Time (years)", type = c("l", "g"))
plot_seasonal(y_stl)
plot_trend(y_stl)
plot_cycle(y_stl)
plot_rembycycle(y_stl)

# if you don't want to use a time series object:
y_stl <- stlplus(y, t = as.vector(time(y)), n.p = 12,
  l.window = 13, t.window = 19, s.window = 35, s.degree = 1,
  sub.labels = substr(month.name, 1, 3))

# with an outlier
y2 <- co2
y2[200] <- 300

y2_stl <- stlplus(y2, t = as.vector(time(y2)), n.p = 12,
  l.window = 13, t.window = 19, s.window = 35, s.degree = 1,
  sub.labels = substr(month.name, 1, 3), outer = 10)

plot(y2_stl, ylab = "CO2 Concentration (ppm)", xlab = "Time (years)")
plot_seasonal(y2_stl)
plot_trend(y2_stl)
plot_cycle(y2_stl)
plot_rembycycle(y2_stl)

# compare to R's stl

x1 <- stlplus(co2, t = as.vector(time(co2)), n.p = 12,
  l.window = 13, t.window = 19, s.window = 11, s.degree = 1,
  sub.labels = substr(month.name, 1, 3))

x2 <- stl(co2, l.window = 13, t.window = 19, s.window = 11, s.degree = 1)

# will be different due to interpolation differences
plot(seasonal(x1) - seasonal(x2))

# but not if all jump parameters are 1
x1 <- stlplus(co2, t = as.vector(time(co2)), n.p = 12,
  l.window = 13, t.window = 19, s.window = 11, s.degree = 1,
  sub.labels = substr(month.name, 1, 3),
  s.jump = 1, t.jump = 1, l.jump = 1)

x2 <- stl(co2, l.window = 13, t.window = 19, s.window = 11, s.degree = 1,
  s.jump = 1, t.jump = 1, l.jump = 1)

plot(seasonal(x1) - seasonal(x2))
```

