---
title: "Lab 2"
author: "Lucas Finke"
date: "2023-09-15"
output: pdf_document
---

The Following is Lab 2.

```{R}
require(MASS)
attach(Animals)
```

```{R}
dotchart(log(body),row.names(Animals),xlab="log(body)")
s <- sort.list(body) 

dotchart(log(body[s]),row.names(Animals[s,]),xlab="log(body)")

```

The above plot is a dot chart of the log(body) size of each animal in the Animal file. Since they were out of order at first, sort.list was used to allow the chart look more like a curve rather than a scatter plot by putting the smallest animals closer to the margin on the y axis.

```{R HOH Cat Data}
attach(cats)
sex <- levels(Sex)
sex
plot(Bwt,Hwt,type="n",xlab="Body",ylab="Heart") # axes only
for(i in 1:2) points(Bwt[Sex==sex[i]],pch=2+i)
text(Bwt,Hwt,c("*","+")[Sex])
BwtF <- mean(Bwt[Sex=="F"])
Bmeans <- tapply(Bwt,Sex,mean)
Hmeans <- tapply(Hwt,Sex,mean)
symbols(Bmeans,Hmeans,circles=c(1,1), inches=0.05,add=T)
hF <- chull(xF <- as.matrix(cats[Sex=="F",-1]))
hM <- chull(xM <- as.matrix(cats[Sex=="M",-1]))
polygon(xF[hF,],dens=5,angle=45)
polygon(xM[hM,],dens=5,angle=135)
```

In this chunk, heart and body weight were plotted against each other one using a simple loop and the other using a similar approach but with less text.Lastly, polygons were placed to show the convex hull of each of the cat's gender.

```{R}
nam <- c(row.names(Animals),row.names(mammals))
dup <- duplicated(nam)
AnimalsALL <- rbind(Animals,mammals)[!dup,]
rm(dup,nam)
```

Above, duplicate data frame entries were bound together by rows and stacked on top of each other.

```{R}
setwd("C:/Users/Lucas/Downloads/Kuhnert+Venables-R_Course_Notes/Datasets")
read.csv("houses.csv")
house <-read.csv("houses.csv")
attach(house)
house
rms <- factor(Rooms)
age <- factor(cut(Age,3))
cht <- CentralHeating
houseT <- transform(house,rms+factor(Rooms), age=factor(cut(Age,3)),cht=CentralHeating)
Fij <-table(Age,Block)
Eij <- outer(table(Age),table(Block))/sum(Fij)
chisq.test
fisher.test
```

In this chunk, Tuggeranong Houses data frame was read since it was not apart of the MASS data set. 3 classes were made as a factor from this data then transformed to a new data frame.

```{R Anorexia Data}
attach(anorexia[anorexia$Treat=="Cont",])
t.test(Prewt,Postwt,paired=T)
t.test(Prewt,Postwt)
```

Anorexia data was used to test the hypothesis previously made by the study to which a t test and a two sample t test were compared to each other. From there, a co-plot was set to compare the weight of the patient pre treatment and post treatment for each group below.

```{R}
attach(anorexia)
panel.fn <- function(x,y,...){
points(x,y,pch=3)
  abline(lm(y~x),col="blue")}
par(mar=c(1,1,1,1))
coplot(Postwt ~ Prewt | Treat,panel=panel.fn)

```

```         
```
